export const PROFILE_DATA = 'PROFILE_DATA';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_PATCH = 'PROFILE_PATCH';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_STATUS = 'PROFILE_STATUS';
export const PROFILE_FOLLOWING = 'PROFILE_FOLLOWING';
export const PROFILE_FOLLOWERS = 'PROFILE_FOLLOWERS';
