export const PROFILE_DATA = 'PROFILE_DATA';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_PATCH = 'PROFILE_PATCH';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_FOLLOWING = 'PROFILE_FOLLOWING';
export const PROFILE_FOLLOWERS = 'PROFILE_FOLLOWERS';
